<<<<<<< HEAD
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
#신석희 mac db 연결(학원컴퓨터는 이거 지우고 하셔야합니다)
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1?useUnicode=true&characterEncoding=UTF-8
spring.datasource.url=jdbc:oracle:thin:@112.221.156.34:8131:orcl
spring.datasource.username=UNIVOLL
spring.datasource.password=UNIVOLL
#spring.datasource.url=jdbc:oracle:thin:@112.221.156.34:8131:orcl
=======
spring.application.name=UNIVOL

# Oracle DB ì°ê²°
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


#신석희 mac db 연결(학원컴퓨터는 이거 지우고 하셔야합니다)
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1?useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=UNIVOLL
spring.datasource.password=UNIVOLL
spring.datasource.url=jdbc:oracle:thin:@112.221.156.34:8131:orcl
>>>>>>> c2061f78d29fb52c1eff59aef209fde79ffca6ba


# MyBatis ì¤ì 
mybatis.mapper-locations=classpath:mappers/**/*.xml
mybatis.type-aliases-package=com.univol.member.model.vo
mybatis.configuration.map-underscore-to-camel-case=true

# Thymeleaf ì¤ì 
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8

#mac 한글 설정
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.datasource.hikari.connection-init-sql=ALTER SESSION SET NLS_LANGUAGE='KOREAN' NLS_TERRITORY='KOREA'