-- ========================================
-- UNIVOL 프로젝트 데이터베이스 스크립트 (수정 버전)
-- 시퀀스 문법 수정 (NOMAXVALUE 제거)
-- ========================================

-- 시퀀스 생성 (단순 문법)
CREATE SEQUENCE SEQ_USERS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_POST START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_REPLY START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_VOLUNTEER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_APPLY START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_REVIEW START WITH 1 INCREMENT BY 1;

-- ========================================
-- 테이블 생성
-- ========================================

-- 사용자 테이블
CREATE TABLE USERS (
    USER_ID VARCHAR2(50) PRIMARY KEY,
    USER_NAME VARCHAR2(100) NOT NULL,
    USER_PW VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE,
    PHONE VARCHAR2(20),
    ADDRESS VARCHAR2(300),
    PROFILE_IMG VARCHAR2(500),
    CREATED_AT DATE DEFAULT SYSDATE
);

-- 게시글 테이블
CREATE TABLE POST (
    P_NUMBER NUMBER PRIMARY KEY,
    P_TITLE VARCHAR2(200) NOT NULL,
    CONTENTS VARCHAR2(4000) NOT NULL,
    P_TYPE CHAR(1) NOT NULL, -- 'V': 봉사, 'R': 후기/댓글
    USER_ID VARCHAR2(50) NOT NULL,
    P_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_POST_USER FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);

-- 댓글 테이블
CREATE TABLE REPLY (
    C_NUMBER NUMBER PRIMARY KEY,
    COMMENTS VARCHAR2(2000) NOT NULL,
    C_DATE DATE DEFAULT SYSDATE,
    P_NUMBER NUMBER NOT NULL,
    USER_ID VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_REPLY_POST FOREIGN KEY(P_NUMBER) REFERENCES POST(P_NUMBER),
    CONSTRAINT FK_REPLY_USER FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);

-- 봉사 활동 테이블
CREATE TABLE VOLUNTEER (
    V_NUMBER NUMBER PRIMARY KEY,
    V_NAME VARCHAR2(200) NOT NULL,
    V_DATE DATE,
    LOCATION VARCHAR2(300),
    P_NUMBER NUMBER NOT NULL,
    CONSTRAINT FK_VOLUNTEER_POST FOREIGN KEY(P_NUMBER) REFERENCES POST(P_NUMBER)
);

-- 신청 테이블
CREATE TABLE APPLY (
    A_NUMBER NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(50) NOT NULL,
    P_NUMBER NUMBER NOT NULL,
    APPLY_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(50) DEFAULT '대기',
    CONSTRAINT FK_APPLY_USER FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_APPLY_POST FOREIGN KEY(P_NUMBER) REFERENCES POST(P_NUMBER)
);

-- 게시글 좋아요 테이블
CREATE TABLE P_LIKE (
    USER_ID VARCHAR2(50),
    P_NUMBER NUMBER,
    PRIMARY KEY (USER_ID, P_NUMBER),
    CONSTRAINT FK_P_LIKE_USER FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_P_LIKE_POST FOREIGN KEY(P_NUMBER) REFERENCES POST(P_NUMBER)
);

-- 댓글 좋아요 테이블
CREATE TABLE C_LIKE (
    USER_ID VARCHAR2(50),
    C_NUMBER NUMBER,
    PRIMARY KEY (USER_ID, C_NUMBER),
    CONSTRAINT FK_C_LIKE_USER FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_C_LIKE_REPLY FOREIGN KEY(C_NUMBER) REFERENCES REPLY(C_NUMBER)
);

-- 리뷰 테이블
CREATE TABLE REVIEW (
    REVIEW_ID NUMBER PRIMARY KEY,
    P_NUMBER NUMBER NOT NULL,
    USER_ID VARCHAR2(50) NOT NULL,
    RATING NUMBER(2,1),
    REVIEW_TEXT VARCHAR2(2000),
    CREATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_REVIEW_POST FOREIGN KEY(P_NUMBER) REFERENCES POST(P_NUMBER),
    CONSTRAINT FK_REVIEW_USER FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);

-- ========================================
-- 트리거 생성 (시퀀스 기반)
-- ========================================

CREATE OR REPLACE TRIGGER TRG_POST
BEFORE INSERT ON POST
FOR EACH ROW
BEGIN
    IF :NEW.P_NUMBER IS NULL THEN
        SELECT SEQ_POST.NEXTVAL INTO :NEW.P_NUMBER FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_REPLY
BEFORE INSERT ON REPLY
FOR EACH ROW
BEGIN
    IF :NEW.C_NUMBER IS NULL THEN
        SELECT SEQ_REPLY.NEXTVAL INTO :NEW.C_NUMBER FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_VOLUNTEER
BEFORE INSERT ON VOLUNTEER
FOR EACH ROW
BEGIN
    IF :NEW.V_NUMBER IS NULL THEN
        SELECT SEQ_VOLUNTEER.NEXTVAL INTO :NEW.V_NUMBER FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_APPLY
BEFORE INSERT ON APPLY
FOR EACH ROW
BEGIN
    IF :NEW.A_NUMBER IS NULL THEN
        SELECT SEQ_APPLY.NEXTVAL INTO :NEW.A_NUMBER FROM DUAL;
    END IF;
END;
/

-- ========================================
-- 테스트 데이터 삽입 (원본 데이터)
-- ========================================

-- 사용자 데이터
INSERT INTO USERS (USER_ID, USER_NAME, USER_PW, EMAIL, PHONE)
VALUES ('user1', '김철수', 'pw1234', 'user1@email.com', '010-1234-5678');
INSERT INTO USERS (USER_ID, USER_NAME, USER_PW, EMAIL, PHONE)
VALUES ('user2', '이영희', 'pw1234', 'user2@email.com', '010-2345-6789');
INSERT INTO USERS (USER_ID, USER_NAME, USER_PW, EMAIL, PHONE)
VALUES ('user3', '박민준', 'pw1234', 'user3@email.com', '010-3456-7890');
INSERT INTO USERS (USER_ID, USER_NAME, USER_PW, EMAIL, PHONE)
VALUES ('user4', '최수진', 'pw1234', 'user4@email.com', '010-4567-8901');
INSERT INTO USERS (USER_ID, USER_NAME, USER_PW, EMAIL, PHONE)
VALUES ('user5', '정한솔', 'pw1234', 'user5@email.com', '010-5678-9012');
INSERT INTO USERS (USER_ID, USER_NAME, USER_PW, EMAIL, PHONE)
VALUES ('user6', '조유미', 'pw1234', 'user6@email.com', '010-6789-0123');
INSERT INTO USERS (USER_ID, USER_NAME, USER_PW, EMAIL, PHONE)
VALUES ('user7', '윤동욱', 'pw1234', 'user7@email.com', '010-7890-1234');
INSERT INTO USERS (USER_ID, USER_NAME, USER_PW, EMAIL, PHONE)
VALUES ('user8', '강미영', 'pw1234', 'user8@email.com', '010-8901-2345');
INSERT INTO USERS (USER_ID, USER_NAME, USER_PW, EMAIL, PHONE)
VALUES ('user9', '홍준호', 'pw1234', 'user9@email.com', '010-9012-3456');

-- 게시글 데이터 (처음 5개만 예시)
INSERT INTO POST (P_TITLE, CONTENTS, P_TYPE, USER_ID)
VALUES ('겨울방학 청소년 멘토링 봉사 모집', '청소년 멘토링 봉사활동입니다.', 'V', 'user1');
INSERT INTO POST (P_TITLE, CONTENTS, P_TYPE, USER_ID)
VALUES ('노인복지관 말벗 봉사 모집', '어르신 말벗 봉사활동입니다.', 'V', 'user2');
INSERT INTO POST (P_TITLE, CONTENTS, P_TYPE, USER_ID)
VALUES ('환경 정화 봉사 모집', '한강 환경 정화 봉사입니다.', 'V', 'user3');
INSERT INTO POST (P_TITLE, CONTENTS, P_TYPE, USER_ID)
VALUES ('장애인 체육대회 보조 봉사', '장애인 체육대회 봉사활동입니다.', 'V', 'user4');
INSERT INTO POST (P_TITLE, CONTENTS, P_TYPE, USER_ID)
VALUES ('지역 아동센터 교육 봉사', '아동센터 교육 봉사활동입니다.', 'V', 'user5');

-- 댓글 데이터 (예시)
INSERT INTO REPLY (COMMENTS, P_NUMBER, USER_ID)
VALUES ('좋은 봉사네요!', 1, 'user2');
INSERT INTO REPLY (COMMENTS, P_NUMBER, USER_ID)
VALUES ('저도 신청했어요!', 1, 'user3');

-- 커밋
COMMIT;

-- ========================================
-- 데이터 확인
-- ========================================
-- SELECT * FROM USERS;
-- SELECT * FROM POST;
-- SELECT * FROM REPLY;
